language: php

php:
    - 5.6
    - 7.0

services:
    - mysql

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - mysql -u root -e 'CREATE DATABASE etc;'
    - mysql -u root etc < test/travis.sql

script: vendor/bin/phpunit --verbose

matrix:
    fast_finish: true