language: php

php:
    - 5.6
    - 7.0
    - 7.2
    - 7.3

services:
    - mysql

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS etc;'


script: ./vendor/bin/phpunit

matrix:
    fast_finish: true